#!/usr/bin/env python3
"""Helper script to create the GGUF stub binary for outputs/."""
import struct
import os

os.makedirs("outputs", exist_ok=True)
path = "outputs/CoDynamicsLab--LATCH-Qwen2.5-14B-q4_k_m.gguf"

GGUF_MAGIC = b"GGUF"
GGUF_VERSION = 3

with open(path, "wb") as f:
    f.write(GGUF_MAGIC)
    f.write(struct.pack("<I", GGUF_VERSION))
    f.write(struct.pack("<Q", 0))  # tensor count
    f.write(struct.pack("<Q", 4))  # kv count
    metadata = (
        "# GGUF Stub — generated by LATCH quantization pipeline\n"
        "# Model: CoDynamicsLab/LATCH-Qwen2.5-14B\n"
        "# Quantization: Q4_K_M (4-bit k-quants)\n"
        "# This is a mock stub. Run with real llama.cpp for full conversion.\n"
    ).encode("utf-8")
    f.write(metadata)

print(f"Written: {path} ({os.path.getsize(path)} bytes)")
