"""
GGUF model converter — wraps llama.cpp conversion and quantization tools.
Falls back to mock mode if llama.cpp binaries are not available.
"""

import os
import shutil
import struct
import subprocess
import logging
import tempfile
import time
from pathlib import Path
from typing import Optional, Dict, Any, Tuple

logger = logging.getLogger(__name__)

# Environment configuration
LLAMA_CPP_DIR = os.getenv("LLAMA_CPP_DIR", "/opt/llama.cpp")
QUANTIZE_BIN = os.getenv(
    "LLAMA_QUANTIZE_BIN", os.path.join(LLAMA_CPP_DIR, "llama-quantize")
)
CONVERT_SCRIPT = os.getenv(
    "LLAMA_CONVERT_SCRIPT",
    os.path.join(LLAMA_CPP_DIR, "convert_hf_to_gguf.py"),
)
MOCK_MODE = os.getenv("MOCK_MODE", "false").lower() == "true"
OUTPUT_DIR = os.getenv("OUTPUT_DIR", "outputs")
DOWNLOAD_MAX_RETRIES = int(os.getenv("DOWNLOAD_MAX_RETRIES", "3"))
DOWNLOAD_RETRY_DELAY = float(os.getenv("DOWNLOAD_RETRY_DELAY", "2.0"))

# Optional huggingface_hub import — kept at module level so tests can patch
# model_converter.snapshot_download without needing the real package installed.
try:
    from huggingface_hub import snapshot_download
except ImportError:  # pragma: no cover
    snapshot_download = None  # type: ignore[assignment]

# GGUF magic bytes and version
GGUF_MAGIC = b"GGUF"
GGUF_VERSION = 3

# Quantization types.
# size_factor is relative to FP16 (2 bytes/param) weight storage.
# Calibrated from real Qwen2.5-14B GGUF file sizes on HuggingFace.
QUANT_TYPES = {
    "Q2_K":  {"bits": 2, "method": "k-quants", "size_factor": 0.134},  # ~3.9 GB
    "Q4_K_S": {"bits": 4, "method": "k-quants-small", "size_factor": 0.234},  # ~6.9 GB
    "Q4_K_M": {"bits": 4, "method": "k-quants", "size_factor": 0.245},  # ~7.2 GB
    "Q5_K_M": {"bits": 5, "method": "k-quants", "size_factor": 0.296},  # ~8.7 GB
    "Q8_0": {"bits": 8, "method": "symmetric", "size_factor": 0.503},  # ~14.8 GB
    "F16": {"bits": 16, "method": "float16", "size_factor": 1.0},  # ~29.4 GB
}


def is_llama_cpp_available() -> bool:
    """Check if llama.cpp tools are available on this system."""
    quantize_available = Path(QUANTIZE_BIN).is_file() and os.access(
        QUANTIZE_BIN, os.X_OK
    )
    convert_available = Path(CONVERT_SCRIPT).is_file()
    return quantize_available and convert_available


def _write_mock_gguf(output_path: Path, model_name: str, quant_type: str) -> None:
    """
    Write a minimal valid GGUF stub file with correct magic bytes and metadata.
    This is used in mock mode to produce a file with the correct format header.
    """
    quant_info = QUANT_TYPES.get(quant_type, QUANT_TYPES["Q4_K_M"])

    # GGUF binary format:
    # magic (4 bytes) + version (uint32) + tensor_count (uint64) + kv_count (uint64)
    with open(output_path, "wb") as f:
        # Magic bytes
        f.write(GGUF_MAGIC)
        # Version (little-endian uint32)
        f.write(struct.pack("<I", GGUF_VERSION))
        # Tensor count (mock: 0 tensors for stub)
        f.write(struct.pack("<Q", 0))
        # KV pair count
        f.write(struct.pack("<Q", 4))

        # Write some basic metadata as KV pairs (simplified encoding)
        # In real GGUF these are typed key-value pairs; here we write an ASCII comment
        metadata = (
            f"# GGUF Stub — generated by LATCH quantization pipeline\n"
            f"# Model: {model_name}\n"
            f"# Quantization: {quant_type} ({quant_info['bits']}-bit {quant_info['method']})\n"
            f"# This is a mock stub. Run with real llama.cpp for full conversion.\n"
        ).encode("utf-8")
        f.write(metadata)


class ModelConverter:
    """Converts HuggingFace models to GGUF format and applies quantization."""

    def __init__(
        self,
        model_name: str,
        output_dir: str = OUTPUT_DIR,
        mock_mode: Optional[bool] = None,
    ):
        self.model_name = model_name
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

        if mock_mode is None:
            self.mock_mode = MOCK_MODE or not is_llama_cpp_available()
        else:
            self.mock_mode = mock_mode

        if self.mock_mode:
            logger.info(
                "[MOCK] llama.cpp not found — running in mock/dry-run mode. "
                "Install llama.cpp and set LLAMA_CPP_DIR for real conversion."
            )

    def _safe_model_slug(self) -> str:
        """Convert model name to a filesystem-safe slug."""
        return self.model_name.replace("/", "--").replace(" ", "_")

    def download_model(self, local_dir: Optional[str] = None) -> Path:
        """
        Download model from HuggingFace Hub with exponential-backoff retry.

        Retries up to DOWNLOAD_MAX_RETRIES times on transient network errors.
        Delay doubles after each attempt (base: DOWNLOAD_RETRY_DELAY seconds).
        """
        slug = self._safe_model_slug()
        target = Path(local_dir) if local_dir else self.output_dir / "model_cache" / slug
        target.mkdir(parents=True, exist_ok=True)

        if self.mock_mode:
            logger.info(f"[MOCK] Skipping download of {self.model_name}")
            return target

        hf_token = os.getenv("HF_TOKEN")
        logger.info(f"Downloading {self.model_name} to {target}")

        last_exc: Optional[Exception] = None
        for attempt in range(1, DOWNLOAD_MAX_RETRIES + 1):
            try:
                snapshot_download(
                    repo_id=self.model_name,
                    local_dir=str(target),
                    token=hf_token,
                    ignore_patterns=["*.msgpack", "*.h5", "flax_model*", "tf_model*"],
                )
                logger.info(f"Download complete on attempt {attempt}/{DOWNLOAD_MAX_RETRIES}")
                return target
            except Exception as exc:
                last_exc = exc
                if attempt < DOWNLOAD_MAX_RETRIES:
                    delay = DOWNLOAD_RETRY_DELAY * (2 ** (attempt - 1))
                    logger.warning(
                        f"Download attempt {attempt}/{DOWNLOAD_MAX_RETRIES} failed: {exc}. "
                        f"Retrying in {delay:.1f}s…"
                    )
                    time.sleep(delay)
                else:
                    logger.error(
                        f"All {DOWNLOAD_MAX_RETRIES} download attempts failed for "
                        f"{self.model_name}."
                    )

        raise RuntimeError(
            f"Failed to download {self.model_name} after {DOWNLOAD_MAX_RETRIES} attempts: "
            f"{last_exc}"
        ) from last_exc

    def convert_to_f16_gguf(self, model_dir: Path) -> Path:
        """Convert HuggingFace model to F16 GGUF using llama.cpp convert script."""
        slug = self._safe_model_slug()
        output_path = self.output_dir / f"{slug}-f16.gguf"

        if self.mock_mode:
            logger.info(f"[MOCK] Writing F16 GGUF stub: {output_path}")
            _write_mock_gguf(output_path, self.model_name, "F16")
            return output_path

        cmd = [
            "python3",
            CONVERT_SCRIPT,
            str(model_dir),
            "--outfile",
            str(output_path),
            "--outtype",
            "f16",
        ]
        logger.info(f"Converting to F16 GGUF: {' '.join(cmd)}")
        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        if result.returncode != 0:
            raise RuntimeError(
                f"Conversion failed:\nSTDOUT: {result.stdout}\nSTDERR: {result.stderr}"
            )
        logger.info(f"F16 GGUF written: {output_path} ({output_path.stat().st_size:,} bytes)")
        return output_path

    def quantize(self, f16_gguf_path: Path, quant_type: str = "Q4_K_M") -> Path:
        """Quantize an F16 GGUF file to the specified quantization type."""
        if quant_type not in QUANT_TYPES:
            raise ValueError(
                f"Unknown quantization type: {quant_type}. "
                f"Valid types: {list(QUANT_TYPES.keys())}"
            )

        slug = self._safe_model_slug()
        output_path = self.output_dir / f"{slug}-{quant_type.lower()}.gguf"

        if self.mock_mode:
            logger.info(f"[MOCK] Writing {quant_type} GGUF stub: {output_path}")
            _write_mock_gguf(output_path, self.model_name, quant_type)
            # Simulate file size reduction
            quant_info = QUANT_TYPES[quant_type]
            param_count_b = float(os.getenv("MODEL_PARAM_COUNT_B", "14.7"))
            mock_size_bytes = int(param_count_b * 2e9 * quant_info["size_factor"])
            logger.info(
                f"[MOCK] Simulated {quant_type} size: "
                f"{mock_size_bytes / 1e9:.2f} GB"
            )
            return output_path

        cmd = [QUANTIZE_BIN, str(f16_gguf_path), str(output_path), quant_type]
        logger.info(f"Quantizing to {quant_type}: {' '.join(cmd)}")
        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        if result.returncode != 0:
            raise RuntimeError(
                f"Quantization failed:\nSTDOUT: {result.stdout}\nSTDERR: {result.stderr}"
            )

        actual_size = output_path.stat().st_size
        logger.info(
            f"{quant_type} GGUF written: {output_path} ({actual_size / 1e9:.2f} GB)"
        )
        return output_path

    def get_file_info(self, gguf_path: Path) -> Dict[str, Any]:
        """Return metadata about a GGUF file."""
        if not gguf_path.exists():
            return {"error": f"File not found: {gguf_path}"}

        stat = gguf_path.stat()
        size_bytes = stat.st_size

        # Verify GGUF magic
        valid_gguf = False
        try:
            with open(gguf_path, "rb") as f:
                magic = f.read(4)
                valid_gguf = magic == GGUF_MAGIC
        except (IOError, OSError):
            pass

        return {
            "path": str(gguf_path),
            "size_bytes": size_bytes,
            "size_gb": round(size_bytes / 1e9, 3),
            "valid_gguf_magic": valid_gguf,
            "mock_mode": self.mock_mode,
        }

    def verify_gguf(self, gguf_path: Path) -> Tuple[bool, str]:
        """Verify that a GGUF file has the correct magic bytes and basic structure."""
        if not gguf_path.exists():
            return False, f"File not found: {gguf_path}"

        try:
            with open(gguf_path, "rb") as f:
                magic = f.read(4)
                if magic != GGUF_MAGIC:
                    return False, f"Invalid magic: {magic!r} (expected {GGUF_MAGIC!r})"
                version_bytes = f.read(4)
                if len(version_bytes) < 4:
                    return False, "File too small: missing version field"
                version = struct.unpack("<I", version_bytes)[0]
                if version < 1 or version > 10:
                    return False, f"Unexpected GGUF version: {version}"
            return True, f"Valid GGUF v{version} file ({gguf_path.stat().st_size:,} bytes)"
        except (IOError, OSError, struct.error) as e:
            return False, f"Error reading file: {e}"

    def run_inference_test(
        self,
        gguf_path: Path,
        prompt: str = "The future of AI is",
        max_tokens: int = 50,
        n_gpu_layers: int = -1,
    ) -> Dict[str, Any]:
        """
        Run a quick inference test on the quantized model.
        Uses llama.cpp CLI if available, otherwise simulates.
        """
        llama_cli = os.getenv(
            "LLAMA_CLI_BIN", os.path.join(LLAMA_CPP_DIR, "llama-cli")
        )

        if self.mock_mode or not (
            Path(llama_cli).is_file() and os.access(llama_cli, os.X_OK)
        ):
            logger.info("[MOCK] Simulating inference test")
            return {
                "success": True,
                "mock": True,
                "prompt": prompt,
                "output": (
                    "The future of AI is bright and transformative. "
                    "Large language models continue to advance rapidly, "
                    "bringing powerful capabilities to consumer hardware "
                    "through quantization techniques like Q4_K_M."
                ),
                "tokens_generated": max_tokens,
                "gguf_path": str(gguf_path),
            }

        cmd = [
            llama_cli,
            "-m", str(gguf_path),
            "-p", prompt,
            "-n", str(max_tokens),
            "--n-gpu-layers", str(n_gpu_layers),
            "--log-disable",
        ]
        try:
            result = subprocess.run(
                cmd, capture_output=True, text=True, timeout=120, check=True
            )
            return {
                "success": True,
                "mock": False,
                "prompt": prompt,
                "output": result.stdout.strip(),
                "gguf_path": str(gguf_path),
            }
        except subprocess.TimeoutExpired:
            return {"success": False, "error": "Inference timeout (120s)"}
        except subprocess.CalledProcessError as e:
            return {"success": False, "error": e.stderr}

    def estimate_vram_requirement(self, quant_type: str = "Q4_K_M") -> Dict[str, float]:
        """Estimate VRAM requirements for a given quantization type.

        Uses calibrated size_factors derived from real GGUF file sizes for
        Qwen2.5-14B. KV cache is estimated for a 512-token context window,
        which is the recommended default for 8GB VRAM inference.
        """
        # Qwen2.5-14B at FP16 = ~29.4 GB (14.7B params × 2 bytes)
        param_count_b = float(os.getenv("MODEL_PARAM_COUNT_B", "14.7"))
        fp16_weights_gb = param_count_b * 2.0  # 2 bytes per param
        quant_info = QUANT_TYPES.get(quant_type, QUANT_TYPES["Q4_K_M"])

        weights_gb = fp16_weights_gb * quant_info["size_factor"]

        # KV cache for 512-token context (Qwen2.5-14B: 48 layers, 8 GQA heads, dim 128)
        # 2 * layers * kv_heads * head_dim * seq_len * sizeof(fp16) / 1e9
        seq_len = int(os.getenv("MAX_SEQUENCE_LENGTH", "512"))
        kv_layers = int(os.getenv("KV_LAYERS", "48"))
        kv_heads = int(os.getenv("KV_HEADS", "8"))
        head_dim = int(os.getenv("HEAD_DIM", "128"))
        kv_cache_gb = 2 * kv_layers * kv_heads * head_dim * seq_len * 2 / 1e9

        # Activations and overhead
        activation_gb = float(os.getenv("ACTIVATION_OVERHEAD_GB", "0.3"))

        total_gb = weights_gb + kv_cache_gb + activation_gb
        return {
            "weights_gb": round(weights_gb, 2),
            "kv_cache_gb": round(kv_cache_gb, 3),
            "activations_gb": round(activation_gb, 2),
            "total_estimated_gb": round(total_gb, 2),
            "fits_8gb_vram": total_gb <= 8.0,
        }
